language: node_js
node_js:
- 12
branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
- cd ui && npm ci

script:
- npm run build

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - me@michaelkohler.info