name: Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Start fetch
      run: env BUGZILLA_TOKEN=${{ secrets.BUGZILLA_TOKEN }} npm start
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add data changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
