name: Update

on:
  schedule:
    # - cron:  '0 0 * * *'
    - cron:  '43 14 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Start fetch
      run: env BUGZILLA_TOKEN=${{ secrets.BUGZILLA_TOKEN }} npm start
